server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_cart
    username: root
    password: kavita
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      enabled: true

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: leena1ver@gmail.com
    password: fktdaeydfjycwjta
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    '[com.ecom.shopping_cart.controllers]': info
  file:
    path: logs
  pattern:
    file: '%d {yyyy-MM-dd HH:mm:ss} [%thread] %msg%n'



