server:
  port: 9091

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"

info:
  application:
    name: 'Shopping_cart'
    description: 'Shopping_cart'
    version: '0.0.1-SNAPSHOT'
  techstack:
    java: 17
    springboot: 3.1.2
    database: MySQL

#springdoc:
#  api-docs:
#      enabled: true
#      path: /v3/api-docs
#  swagger-ui:
#      path: /swagger-ui.html

springfox:
  documentation:
    swagger-ui:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_cart
    username: root
    password: kavita
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      enabled: true

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: leena1ver@gmail.com
    password: fktdaeydfjycwjta
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    '[com.ecom.shopping_cart.controllers]': DEBUG
  file:
    path: logs
  pattern:
    file: '%d {yyyy-MM-dd HH:mm:ss} [%thread] %msg%n'



